# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2023-01-19 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64, verbose_name='Referencia')),
                ('description', models.CharField(default='', max_length=255, verbose_name='Descripci\xf3n')),
                ('unit', models.CharField(default='', max_length=64, verbose_name='Unidad')),
                ('value', models.FloatField(default=0, verbose_name='Valor')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='Color (RGB con # al principio)')),
                ('color_font', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Color de texto (RGB con # al principio)')),
            ],
            options={
                'ordering': ['-value'],
                'verbose_name': 'Referencia WRF',
                'verbose_name_plural': 'Referencias WRF',
            },
        ),
        migrations.CreateModel(
            name='WrfLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=10, verbose_name='T\xedtulo de la capa WRF')),
                ('description', models.CharField(max_length=64, verbose_name='Descripci\xf3n')),
                ('lat_point_1', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Latitud punto 1')),
                ('long_point_1', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Longitud punto 1')),
                ('lat_point_2', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Latitud punto 2')),
                ('long_point_2', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Longitud punto 2')),
                ('is_active', models.BooleanField(default=True, verbose_name='Radar activo?')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': 'Capa WRF',
                'verbose_name_plural': 'Capas WRF',
            },
        ),
        migrations.CreateModel(
            name='WrfProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_key', models.CharField(default='', max_length=10, unique=True, verbose_name='C\xf3digo de Producto WRF (Nombre de la imagen)')),
                ('product_title', models.CharField(default='', max_length=32, verbose_name='T\xedtulo de Producto WRF')),
                ('product_description', models.TextField(default='', verbose_name='Descripci\xf3n de Producto')),
                ('enabled', models.BooleanField(default=True, verbose_name='Se muestra?')),
                ('see_in_open', models.BooleanField(default=False, verbose_name='Mostrar al inicio')),
            ],
            options={
                'ordering': ['product_title'],
                'verbose_name': 'Producto WRF',
                'verbose_name_plural': 'Productos WRF',
            },
        ),
        migrations.AddField(
            model_name='reference',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='api_wrf.WrfProduct'),
        ),
    ]
