version: '3.4'
services:
  proxy:
    build:
      context: .
      dockerfile: ./deploy/nginx/Dockerfile
    restart: always
    container_name: nginx_webmet
    depends_on:
      - webmet
    ports:
      - "0.0.0.0:85:80"
  database:
    # image: postgres
    image: postgres:11.3
    restart: always
    environment:
    - POSTGRES_PASSWORD=gu3bm3t
    - POSTGRES_USER=webmet
    - POSTGRES_DB=webmet
    - PGDATA=/var/lib/postgresql/data
    volumes:
    - db_data:/var/lib/postgresql
    - db_data2:/var/lib/postgresql/data
  webmet:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    ports:
    - "8005:8000"
    environment:
      - DEBUG=True
      - DOMAIN=localhost
      - DJANGO_SETTINGS=local
      - DB_HOST=database      
      - PYTHONUNBUFFERED=0
    volumes:
    - .:/app/website
    - ../genpro_radares/test_data/genpro_product_outputs:/app/website/media/radares/images/
    depends_on:
    - database
    restart: always

volumes: 
  db_data:
  db_data2: {}