# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radar',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Cod. Radar')),
                ('title', models.CharField(max_length=64, verbose_name='Tit. Radar')),
                ('description', models.CharField(max_length=64, verbose_name='Descrip.')),
                ('center_lat', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitud centro')),
                ('center_long', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Longitud centro')),
                ('img_radio', models.IntegerField(choices=[(120, '120km'), (240, '240km'), (480, '480km')], verbose_name='R\xe1dio de la Imagen (kmts)')),
            ],
        ),
        migrations.CreateModel(
            name='RadarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='radares/images')),
                ('polarimetric_var', models.CharField(choices=[('TH', 'TH'), ('TV', 'TV'), ('TDR', 'TDR'), ('PHIDP', 'PHIDP'), ('KDP', 'KDP'), ('RHOHV', 'RHOHV'), ('VRAD', 'VRAD'), ('WRAD', 'WRAD'), ('HID ', 'HID ')], default='', max_length=10, verbose_name='Variable Polarim\xe9trica')),
                ('date', models.DateTimeField(verbose_name='Fecha y hora')),
                ('strategy', models.IntegerField(default=0, verbose_name='Estrategia')),
                ('scanning', models.IntegerField(default=0, verbose_name='Num. Barrido')),
                ('radar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_radares.Radar')),
            ],
        ),
    ]
