# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_radares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radar',
            name='center_lat',
            field=models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Latitud centro'),
        ),
        migrations.AlterField(
            model_name='radar',
            name='center_long',
            field=models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Longitud centro'),
        ),
        migrations.AlterField(
            model_name='radarimage',
            name='polarimetric_var',
            field=models.CharField(choices=[('TH', 'TH'), ('TV', 'TV'), ('TDR', 'TDR'), ('PHIDP', 'PHIDP'), ('KDP', 'KDP'), ('RHOHV', 'RHOHV'), ('VRAD', 'VRAD'), ('WRAD', 'WRAD'), ('HID', 'HID')], default='', max_length=10, verbose_name='Variable Polarim\xe9trica'),
        ),
    ]
