# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2023-01-19 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_radares', '0002_auto_20170704_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='ID de Estrategia')),
                ('description', models.CharField(default='', max_length=255, verbose_name='Descripci\xf3n')),
            ],
            options={
                'verbose_name': 'Volumen',
                'verbose_name_plural': 'Estrategias',
            },
        ),
        migrations.CreateModel(
            name='RadarProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_key', models.CharField(default='', max_length=10, verbose_name='C\xf3digo de Producto (Nombre de la imagen)')),
                ('product_title', models.CharField(default='', max_length=10, verbose_name='T\xedtulo de Producto')),
                ('product_description', models.TextField(default='', verbose_name='Descripci\xf3n de Producto')),
                ('enabled', models.BooleanField(default=True, verbose_name='Se muestra?')),
                ('see_in_open', models.BooleanField(default=False, verbose_name='Mostrar al inicio')),
            ],
            options={
                'ordering': ['product_key'],
                'verbose_name': 'Producto de Radar',
                'verbose_name_plural': 'Productos de Radar',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64, verbose_name='Referencia')),
                ('description', models.CharField(default='', max_length=255, verbose_name='Descripci\xf3n')),
                ('unit', models.CharField(default='', max_length=64, verbose_name='Unidad')),
                ('value', models.FloatField(default=0, verbose_name='Valor')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='Color (RGB con # al principio)')),
                ('color_font', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Color de texto (RGB con # al principio)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='api_radares.RadarProduct')),
            ],
            options={
                'ordering': ['-value'],
                'verbose_name': 'Referencia',
                'verbose_name_plural': 'Referencias',
            },
        ),
        migrations.CreateModel(
            name='Volumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Volumen',
                'verbose_name_plural': 'Volumenes',
            },
        ),
        migrations.AlterModelOptions(
            name='radar',
            options={'verbose_name': 'Radar', 'verbose_name_plural': 'Radares'},
        ),
        migrations.AlterModelOptions(
            name='radarimage',
            options={'verbose_name': 'Imagen de Radar', 'verbose_name_plural': 'Imagenes de Radares'},
        ),
        migrations.AddField(
            model_name='radar',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Radar activo?'),
        ),
        migrations.AddField(
            model_name='radar',
            name='point1_lat',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=14, verbose_name='Latitud Norte'),
        ),
        migrations.AddField(
            model_name='radar',
            name='point1_long',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=14, verbose_name='Longitud Este'),
        ),
        migrations.AddField(
            model_name='radar',
            name='point2_lat',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=14, verbose_name='Latitud Sur'),
        ),
        migrations.AddField(
            model_name='radar',
            name='point2_long',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=14, verbose_name='Longitud Oeste'),
        ),
        migrations.AddField(
            model_name='radarimage',
            name='show_me',
            field=models.BooleanField(default=True, verbose_name='Se muestra?'),
        ),
        migrations.AddField(
            model_name='radarimage',
            name='sweep',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='\xc1ngulo de la elevacion'),
        ),
        migrations.AlterField(
            model_name='radarimage',
            name='polarimetric_var',
            field=models.CharField(default='', max_length=10, verbose_name='Variable Polarim\xe9trica'),
        ),
        migrations.AddField(
            model_name='estrategia',
            name='volumenes',
            field=models.ManyToManyField(related_name='estrategias', to='api_radares.Volumen'),
        ),
    ]
