# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2023-01-19 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Temperatura')),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Humedad')),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Presi\xf3n')),
                ('wind_speed_max', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Direcci\xf3n de viento en rafaga m\xe1xima')),
                ('wind_speed_avg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Direcci\xf3n de viento promedio')),
                ('wind_deg_max', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Velocidad de viento en rafaga m\xe1xima')),
                ('wind_deg_avg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Velocidad de viento en promedio')),
                ('rain', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Lluvia acumulada')),
            ],
            options={
                'verbose_name': 'Medici\xf3n',
                'verbose_name_plural': 'Mediciones',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='C\xf3digo de la estaci\xf3n')),
                ('title', models.CharField(max_length=128, verbose_name='T\xedtulo de la estaci\xf3n')),
                ('description', models.CharField(max_length=128, verbose_name='Descripci\xf3n')),
                ('brand_name', models.CharField(max_length=64, verbose_name='Marca')),
                ('lat', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Latitud')),
                ('long', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Longitud ')),
            ],
            options={
                'verbose_name': 'Estaci\xf3n',
                'verbose_name_plural': 'Estaciones',
            },
        ),
        migrations.AddField(
            model_name='measure',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_estaciones.Station'),
        ),
    ]
